# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
sudo: required
dist: trusty
before_install:
  - wget http://scip.zib.de/download/release/SCIPOptSuite-5.0.1-Linux.deb
  - sudo dpkg -i SCIPOptSuite-5.0.1-Linux.deb
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - export SCIPOPTDIR="/usr"
  - julia -e 'Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
