## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: bionic
sudo: true
julia:
  - 1.0
  - 1.3
notifications:
  email: false
git:
  depth: 99999999
addons:
  apt:
    packages:
    - libblas3
    - libc6
    - libgcc1
    - libgfortran4
    - libgmp10
    - libgsl23
    - liblapack3
    - libquadmath0
    - libstdc++6
    - libtbb2
    - zlib1g
before_install:
  - export VERSION=7.0.0
  - export DEBFILE=SCIPOptSuite-$VERSION-Linux.deb
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://scip.zib.de/download/release/$DEBFILE; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i $DEBFILE ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir install; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget http://scip.zib.de/download/release/SCIPOptSuite-$VERSION-Darwin.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sh SCIPOptSuite-$VERSION-Darwin.sh --skip-license --prefix=install --exclude-subdir; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export SCIPOPTDIR=$(pwd)/install; fi
# Use default build script.
# script:
#   - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
jobs:
  allow_failures:
    - stage: "MINLPTests"
  include:
    - stage: "MINLPTests"
      julia: 1.0
      os: linux
      script:
        - julia --project=test/MINLPTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/MINLPTests --color=yes test/MINLPTests/run_minlptests.jl
after_success:
  # push coverage results to Codecov, Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("SCIP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(Coveralls.process_folder())'
