# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
sudo: required
dist: trusty
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - wget http://scip.zib.de/download/release/scipoptsuite-4.0.0.tgz
  - tar xzf scipoptsuite-4.0.0.tgz
  - cd scipoptsuite-4.0.0/
  - make SHARED=true GMP=false READLINE=false ZLIB=false scipoptlib
  - export SCIPOPTDIR=`pwd`
  - cd ..
  - julia -e 'Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
