## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
sudo: true
notifications:
  email: false
git:
  depth: 99999999
addons:
  apt:
    packages:
    - libblas3
    - libc6
    - libgcc1
    - libgfortran4
    - libgmp10
    - libgsl23
    - liblapack3
    - libquadmath0
    - libstdc++6
    - libtbb2
    - zlib1g
before_install:
  - export VERSION=7.0.1
  - export DEBFILE=SCIPOptSuite-$VERSION-Linux.deb
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget --no-check-certificate https://scip.zib.de/download/release/$DEBFILE; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i $DEBFILE ; fi
# Use default build script.
# script:
#   - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("SCIP"); Pkg.test("SCIP"; coverage=true)'
jobs:
  allow_failures:
    - stage: "MINLPTests"
  include:
    - os: linux
      julia: 1.0
    - os: linux
      julia: 1.5
    - os: osx
      julia: 1.5
    - stage: "MINLPTests"
      julia: 1.5
      os: linux
      script:
        - julia --project=test/MINLPTests -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=test/MINLPTests --color=yes test/MINLPTests/run_minlptests.jl
after_success:
  # push coverage results to Codecov, Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("SCIP")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(Coveralls.process_folder())'
